name: PlayerTours
description: Manages tours of new players!
main: legorvegenine.PlayerTours
version: 1.7
commands:
   tour:
      description: Manages the current tour for new players.
      usage: /tour list/start/end/count [playername]
   setnewplayerspawn:
      description: Sets the spawn for new players.
      usage: /setnewplayerspawn <x> <y> <z>
   setservername:
      description: Sets the server name for new player welcome message.
      usage: /setservername <name>

permissions:
    cansetnewplayerspawn:
        description: OPs can set the spawn for new players.
        default: op
    cancheckplayertourstats:
        description: Anybody can check how many tours a player has given.
        default: true